apiVersion: apps/v1
kind: Deployment
metadata:
  name: sani-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: be-service
        image: mershab99/be-sani
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: fe-service
        image: mershab99/fe-sani
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      - name: db
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 27017
        env:
        - name: MONGOD_INITDB_ROOT_USERNAME
          value: mongo
        - name: MONGOD_INITDB_ROOT_PASSWORD
          value: pass
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: mongodb-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: be-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: fe-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
