apiVersion: v1
kind: Pod
metadata:
  name: hack-pod
  labels:
    name: hack-pod
spec:
  containers:
    - name: db
      image: mongo
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 27017
      env:
      - name: MONGOD_INITDB_ROOT_USERNAME
        value: mongo
      - name: MONGOD_INITDB_ROOT_PASSWORD
        value: pass
    - name: hack-be
      image: mershab99/be-sani
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
    - name: hack-fe
      image: mershab99/fe-sani
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000